<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RaviRajani" name="Default test" tests="2" failures="1" timestamp="20 Aug 2018 18:43:06 GMT" time="5.069" errors="0">
  <testcase name="firstTest" time="2.024" classname="learningTestNG.Timeouttest"/>
  <testcase name="secondtest" time="3.004" classname="learningTestNG.Timeouttest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.secondtest() didn&amp;apos;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.secondtest() didn't finish within the time-out 3000
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- secondtest -->
</testsuite> <!-- Default test -->
