<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RaviRajani" name="learningTestNG.Timeouttest" tests="2" failures="0" timestamp="20 Aug 2018 18:43:06 GMT" time="5.028" errors="1">
  <testcase name="secondtest" time="3.004" classname="learningTestNG.Timeouttest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.secondtest() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.secondtest() didn't finish within the time-out 3000
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- secondtest -->
  <testcase name="firstTest" time="2.024" classname="learningTestNG.Timeouttest"/>
</testsuite> <!-- learningTestNG.Timeouttest -->
